dao.cliente=STRING
dao.cuenta=BYTE
dao.transaccion=STRING

ruta.clientes=data/clientes.txt
ruta.cuentas=data/cuentas.dat
ruta.depositos=data/depositos.txt
ruta.extracciones=data/extracciones.txt
ruta.transferencias=data/transferencias.txt
ruta.conversiones=data/conversiones.txt
